---
- hosts: localhost
  sudo: yes
  #java_versions: oracle-java8-installer
  tasks:
    - name: dev suites
      apt:
        pkg: build-essential,git,tig,cscope-el,emacs,emacs-goodies-el
    - name: docker
      apt:
        pkg: docker
    - name: basics
      apt:
        pkg: curl,htop,less,tmux,wget,yaml-mode,iftop,dstat

    - include: external-clients-setup.yml
    - include: otp.yml

    - name: Create directory for maven       
      file: path=/usr/local/maven state=directory owner=root group=root mode=0755

    - name: Download Maven
      get_url: >
        url=http://ftp.tsukuba.wide.ad.jp/software/apache/maven/maven-3/3.3.1/binaries/apache-maven-3.3.1-bin.tar.gz
        sha256sum=153564900617218a126f78d2603d060d0a15f19f3ec1689fc2b7692a3c15b9aa
        dest=/usr/local/maven/
    - name: Install Maven
      command: tar xzf apache-maven-3.3.1-bin.tar.gz chdir=/usr/local/maven

    - name: for Riak
      apt:
        pkg: libpam0g-dev


    - name: shell
      command: touch abracadabra

  handlers:
    - name: check
      shell: which emacs