---
- hosts: localhost
  sudo: yes
  #java_versions: oracle-java8-installer
  tasks:
    - name: for Riak CS external clients test
      apt:
        pkg: uuid-runtime,golang,php5-cli,php5-curl,python-virtualenv    

    - name: Install lein
      get_url: >
        url=https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
        dest=/usr/local/bin/lein

    - name: setup lein
      command: chmod 755 /usr/local/bin/lein

    - name: Install PHP with Curl extension for Riak CS
      apt:
        pkg: php5-cli,php5-curl

    - name: Install composer
      shell: curl -sS https://getcomposer.org/installer | php

    - name: Configure composer
      shell: mv composer.phar /usr/local/bin/composer
